name: Application CI

on:
  pull_request:
    branches: [main]

jobs:
  application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run format check
        run: yarn format:check

      - name: Run lint
        run: yarn lint

      - name: Run type check
        run: yarn typescript:check

      - name: Run unit tests in CI environment
        run: yarn test:ci

      - name: Build the application
        run: yarn build
        env:
          UMAMI_WEBSITE_ID: ${{secrets.UMAMI_WEBSITE_ID}}
          UMAMI_WEBSITE_URL: ${{secrets.UMAMI_WEBSITE_URL}}
